### ISSUE TITLE
新手问题

### ISSUE THREAD

**Issue by putao520** [miaomiaoyule/DUIThink#1]
请问这个是一个duilib的设计器项目吗？用的duilib版本有要求吗？可以配合您的这个设计器在vs2022里开发duilib的项目吗？

**Comment by miaomiaoyule** [comment]
你好，这是DUIThink的设计器，与duilib不兼容
Vs2022可以使用，我用的就是2022



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: putao520 ***@***.***&gt;
发送时间: 2024年5月11日 03:22
收件人: miaomiaoyule/DUIThink ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [miaomiaoyule/DUIThink] 新手问题 (Issue #1)





 
请问这个是一个duilib的设计器项目吗？用的duilib版本有要求吗？可以配合您的这个设计器在vs2022里开发duilib的项目吗？

**Comment by putao520** [comment]
大佬,如果只是设计器为什么没有release发布呀~

**Comment by putao520** [comment]
啊,大佬请问设计器支持的是什么版本的duilib呀?

**Comment by miaomiaoyule** [comment]
设计器有发布包，DUIThink库是开源的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: putao520 ***@***.***&gt;
发送时间: 2024年5月11日 22:50
收件人: miaomiaoyule/DUIThink ***@***.***&gt;
抄送: 城南花已开koko ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [miaomiaoyule/DUIThink] 新手问题 (Issue #1)





 
大佬,如果只是设计器为什么没有release发布呀~
